# Generated by Django 4.2.1 on 2023-05-07 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('user_type', models.CharField(max_length=50)),
                ('esstado_civil', models.CharField(max_length=50)),
                ('cpf_estudante', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone_estudante', models.CharField(max_length=9)),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=100, null=True)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('resumo_academico', models.TextField(blank=True, null=True)),
                ('cpf_anfitriao', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone_anfitriao', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao_espaco', models.TextField(blank=True, null=True)),
                ('comodidades', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
