# Generated by Django 4.2.1 on 2023-05-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfil_estado_civil_alter_perfil_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='user_type',
            field=models.CharField(blank=True, choices=[('estudante', 'Estudante'), ('anfitriao', 'Anfitrião')], max_length=50, null=True),
        ),
    ]
