# Generated by Django 4.2.1 on 2023-05-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VagaCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('regras_casa', models.TextField()),
                ('informacoes_familia', models.TextField()),
                ('contato', models.EmailField(max_length=254)),
            ],
        ),
    ]
